version: '3.8'

services:
  # Redis para caché y mensajería
  redis:
    image: redis:7-alpine
    container_name: talentcircle-redis
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - talentcircle-network
    restart: always

  # Backend Java ARM64
  backend:
    image: chuycode/talentcircle-backend:v0.1.1
    container_name: talentcircle-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:talentcircle_db;DB_CLOSE_DELAY=-1
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - VITE_API_BASE_URL=
      - JWT_SECRET=el-secreto-esMuySeguro
      - DISCORD_BOT_TOKEN=MTUwMjQ4MzM3Nzg4OTA4NzU1OQ.Gs2zxI.jbF8-UHf7KongfGzXa2Gyw7sIX07nADt3btjhs
      - DISCORD_GUILD_ID=1018667130964688987

    depends_on:
      redis:
        condition: service_healthy
    networks:
      - talentcircle-network
    restart: unless-stopped

  # Frontend React
  frontend:
    image: chuycode/talentcircle-frontend:v5.0
    container_name: talentcircle-frontend
    # Puertos removidos: el tráfico entra por el gateway
    depends_on:
      - backend
    networks:
      - talentcircle-network
    restart: unless-stopped

  # Nginx Reverse Proxy (Puerta de entrada única)
  gateway:
    image: nginx:alpine
    container_name: talentcircle-gateway
    ports:
      - "1024:80"
    volumes:
      - /home/ubuntu/talentcircle/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - talentcircle-network
    restart: always

volumes:
  redis_data:

networks:
  talentcircle-network:
    driver: bridge